name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - ca-certificates=2022.5.18.1=h5b45459_0
  - certifi=2022.5.18.1=py39hcbf5309_0
  - cffi=1.15.0=py39h2bbff1b_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - cudatoolkit=11.2.2=h933977f_10
  - cudnn=8.1.0.77=h3e0f4f4_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.10.4=h546665d_1
  - graphviz=2.38=hfd603c8_2
  - icu=58.2=ha925a31_3
  - ipykernel=6.9.1=py39haa95532_0
  - ipython=8.3.0=py39haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py39haa95532_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - jsonschema=4.4.0=py39haa95532_0
  - jupyter=1.0.0=py39haa95532_7
  - jupyter_client=7.2.2=py39haa95532_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.0.10=h21b02b4_1005
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - lz4-c=1.9.3=h8ffe710_1
  - markupsafe=2.0.1=py39h2bbff1b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h2bbff1b_1000
  - nbclient=0.5.13=py39haa95532_0
  - nbconvert=6.4.4=py39haa95532_0
  - nbformat=5.3.0=py39haa95532_0
  - nest-asyncio=1.5.5=py39haa95532_0
  - notebook=6.4.11=py39haa95532_0
  - openssl=1.1.1o=h8ffe710_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyautogui=0.9.53=py39hcbf5309_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pymsgbox=1.0.9=pyh9f0ad1d_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyrsistent=0.18.0=py39h196d8e1_0
  - pyscreeze=0.1.27=pyhd8ed1ab_0
  - python=3.9.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytweening=1.0.3=py_0
  - pywin32=302=py39h2bbff1b_2
  - pywinpty=2.0.2=py39h5da7b33_0
  - pyzmq=22.3.0=py39hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py39haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.12=h8ffe710_0
  - tornado=6.1=py39h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - absl-py==1.0.0
    - aggdraw==1.3.14
    - astunparse==1.6.3
    - cachetools==5.1.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - flatbuffers==2.0
    - fonttools==4.33.3
    - gast==0.5.3
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.46.3
    - h5py==3.6.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - joblib==1.1.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - libclang==14.0.1
    - markdown==3.3.7
    - matplotlib==3.5.2
    - numpy==1.22.4
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - pandas==1.4.2
    - pillow==9.1.1
    - pip==22.1
    - protobuf==3.20.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot==1.4.2
    - pyparsing==3.0.9
    - pytz==2022.1
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - seaborn==0.11.2
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.1.0
    - tqdm==4.64.0
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - visualkeras==0.0.2
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - zipp==3.8.0
prefix: D:\Miniconda3\envs\tf
